// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMHwmN-5GdaOzLyrYQKtES-B26b8QEb2U',
    appId: '1:227386123616:web:ce84992de2864c2a092a05',
    messagingSenderId: '227386123616',
    projectId: 'pad-vending-with-flutter-app',
    authDomain: 'pad-vending-with-flutter-app.firebaseapp.com',
    storageBucket: 'pad-vending-with-flutter-app.appspot.com',
    measurementId: 'G-FTL58EFP78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2x7UsU2utFdOOFG7zQJm1JduPeprhaq4',
    appId: '1:227386123616:android:1c4614560c0ea91c092a05',
    messagingSenderId: '227386123616',
    projectId: 'pad-vending-with-flutter-app',
    storageBucket: 'pad-vending-with-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATGbpDhhEruQ4kJwUm6zuY-c0ah8nc0HE',
    appId: '1:227386123616:ios:edaaee32edee5675092a05',
    messagingSenderId: '227386123616',
    projectId: 'pad-vending-with-flutter-app',
    storageBucket: 'pad-vending-with-flutter-app.appspot.com',
    iosBundleId: 'com.example.vendingMachApp',
  );
}
